### ISSUE TITLE
Testes exploratórios

### ISSUE THREAD

**Issue by LucasCiocari** [s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive#1]
[excluir_arquivo_e_pasta.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive/files/2429385/excluir_arquivo_e_pasta.pdf)
[salvar_como_diferente.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive/files/2429386/salvar_como_diferente.pdf)
[download.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive/files/2429387/download.pdf)
[teste_login_upload.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive/files/2429388/teste_login_upload.pdf)
[criar_pasta_e_documento_e_renomear_e_salvar.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive/files/2429389/criar_pasta_e_documento_e_renomear_e_salvar.pdf)
[tentativa_mover_falha.pdf](https://github.com/s2b-teste-2018-2-proj-final-lucas-fab/teste_one_drive/files/2429390/tentativa_mover_falha.pdf)

**Comment by fabianoseller** [comment]
Ambiente doméstico restaurado.
Abri a automação em casa.
Falta rever a falha

**Comment by LucasCiocari** [comment]
Teste do one drive não funcionou. By class, xpath ou afins não funcionaram. Não sei o que fazer...
